CREATE TABLE user
(
  id INTEGER PRIMARY KEY AUTOINCREMENT ,
  mail VARCHAR(120) UNIQUE,
  nom VARCHAR(30),
  prenom VARCHAR(30),
  mdp VARCHAR(160),
  age INTEGER
);

CREATE TABLE ingredient
(
  id INTEGER PRIMARY KEY AUTOINCREMENT ,
  nom VARCHAR(30) UNIQUE
);

CREATE TABLE unite
(
  id INTEGER PRIMARY KEY AUTOINCREMENT ,
  nom VARCHAR(30) UNIQUE
);

CREATE TABLE cocktail
(
  id INTEGER PRIMARY KEY AUTOINCREMENT ,
  nom VARCHAR(120) UNIQUE
);